services:
  db:
    image: postgres:18-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: def7845
      POSTGRES_DB: storage
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass "def7845"

  gateway:
    image: caddy:2-alpine
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - ./logs/caddy:/var/log/caddy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  adminer:
    image: adminer:latest
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db

  redis-web:
    image: rediscommander/redis-commander:latest
    environment:
      # label:host:port:dbIndex:password
      - REDIS_HOSTS=local:redis:6379:0:def7845
    ports:
      - "127.0.0.1:8081:8081"